### ISSUE TITLE
Compilation errors on Ubuntu 14.04

### ISSUE THREAD

**Issue by RonPoon** [dnstap/unbound#1]
1. according to fstrm source, enum records is lowercase, and are the other compilation errors.

dnstap/dnstap.c: In function 'dt_send':
dnstap/dnstap.c:92:13: error: 'FSTRM_RES_SUCCESS' undeclared (first use in this function)
  if (res != FSTRM_RES_SUCCESS)
             ^
dnstap/dnstap.c:92:13: note: each undeclared identifier is reported only once for each function it appears in
dnstap/dnstap.c: In function 'dt_create':
dnstap/dnstap.c:137:7: warning: assignment makes pointer from integer without a cast [enabled by default]
  fopt = fstrm_io_options_init();
       ^
dnstap/dnstap.c:142:36: error: 'fstrm_unix_writer' undeclared (first use in this function)
  fstrm_io_options_set_writer(fopt, fstrm_unix_writer, fuwopt);
                                    ^
dnstap/dnstap.c:143:11: warning: assignment makes pointer from integer without a cast [enabled by default]
  env->fio = fstrm_io_init(fopt, &fio_err);
           ^
dnstap/dnstap.c: In function 'dt_init':
dnstap/dnstap.c:241:10: warning: assignment makes pointer from integer without a cast [enabled by default]
  env->fq = fstrm_io_get_queue(env->fio);
          ^
make: **\* [dnstap.lo] Error 1
1. After some code modification, linker cannot parse the following steps:-

libtool: link: gcc -I. -g -O2 -flto -pthread -I/usr/local/include -I/usr/local/include -o unbound .libs/acl_list.o .libs/cachedump.o .libs/daemon.o .libs/remote.o .libs/stats.o .libs/unbound.o .libs/worker.o .libs/dns.o .libs/infra.o .libs/rrset.o .libs/dname.o .libs/msgencode.o .libs/msgparse.o .libs/msgreply.o .libs/packed_rrset.o .libs/iterator.o .libs/iter_delegpt.o .libs/iter_donotq.o .libs/iter_fwd.o .libs/iter_hints.o .libs/iter_priv.o .libs/iter_resptype.o .libs/iter_scrub.o .libs/iter_utils.o .libs/localzone.o .libs/mesh.o .libs/modstack.o .libs/outbound_list.o .libs/alloc.o .libs/config_file.o .libs/configlexer.o .libs/configparser.o .libs/fptr_wlist.o .libs/locks.o .libs/log.o .libs/mini_event.o .libs/module.o .libs/net_help.o .libs/random.o .libs/rbtree.o .libs/regional.o .libs/rtt.o .libs/dnstree.o .libs/lookup3.o .libs/lruhash.o .libs/slabhash.o .libs/timehist.o .libs/tube.o .libs/winsock_event.o .libs/autotrust.o .libs/val_anchor.o .libs/validator.o .libs/val_kcache.o .libs/val_kentry.o .libs/val_neg.o .libs/val_nsec3.o .libs/val_nsec.o .libs/val_secalgo.o .libs/val_sigcrypt.o .libs/val_utils.o .libs/dnstap.o .libs/dnstap.pb-c.o .libs/netevent.o .libs/listen_dnsport.o .libs/outside_network.o .libs/keyraw.o .libs/sbuffer.o .libs/wire2str.o .libs/parse.o .libs/parseutil.o .libs/rrdef.o .libs/str2wire.o .libs/strlcat.o .libs/strlcpy.o  -lssl -ldl -lcrypto -L/usr/local/lib /usr/local/lib/libfstrm.so /usr/local/lib/libprotobuf-c.so -pthread 
/tmp/ccn63w5W.ltrans6.ltrans.o: In function `dt_send.isra.5.35610':
/root/unbound/dnstap/dnstap.c:90: undefined reference to`fstrm_io_submit'
/tmp/ccn63w5W.ltrans26.ltrans.o: In function `dt_delete':
/root/unbound/dnstap/dnstap.c:254: undefined reference to`fstrm_io_destroy'
/tmp/ccn63w5W.ltrans21.ltrans.o: In function `dt_init':
/root/unbound/dnstap/dnstap.c:242: undefined reference to`fstrm_io_get_queue'
/tmp/ccn63w5W.ltrans21.ltrans.o: In function `dt_create':
/root/unbound/dnstap/dnstap.c:138: undefined reference to`fstrm_io_options_init'
/root/unbound/dnstap/dnstap.c:139: undefined reference to `fstrm_io_options_set_content_type'
/root/unbound/dnstap/dnstap.c:142: undefined reference to`fstrm_io_options_set_num_queues'
/root/unbound/dnstap/dnstap.c:143: undefined reference to `fstrm_io_options_set_writer'
/root/unbound/dnstap/dnstap.c:144: undefined reference to`fstrm_io_init'
/root/unbound/dnstap/dnstap.c:152: undefined reference to `fstrm_io_options_destroy'
/root/unbound/dnstap/dnstap.c:152: undefined reference to`fstrm_io_options_destroy'
collect2: error: ld returned 1 exit status
make: **\* [unbound] Error 1

**Comment by edmonds** [comment]
dnstap is now in mainline Unbound as of 1.5.0, which fixes these compilation errors.

**Comment by shulhi** [comment]
Is there any timeline on 1.5.0 release? I'm having the same issue.

**Comment by edmonds** [comment]
Unbound 1.5.0 was released in November 2014.

**Comment by shulhi** [comment]
Thanks @edmonds I didn't notice dnstap has been integrated into Unbound, thought that it still running on diff repo.
